import { Producto } from '../models/producto.model';

export const DEFAULT_PRODUCTS: Producto[] = [
    {
        id: 1,
        nombre: 'Cappuccino',
        codigo: '1',
        descripcion: 'El balance perfecto entre nuestro café espresso, leche vaporizada y abundante espuma de leche.',
        img: '/assets/coffees-images/cappuccino.png',
        precio: 65,
        precioAnterior: 70,
        isInOferta: true,
    },
    {
        id: 2,
        nombre: 'Café Mocha',
        codigo: '2',
        descripcion: 'Delicioso e intenso chocolate, con café espresso y leche al vapor, coronado con crema batida.',
        img: '/assets/coffees-images/caffe-mocha.png',
        precio: 70,
        precioAnterior: 80,
        isInOferta: true,
    },
    {
        id: 3,
        nombre: 'Espresso Lungo',
        codigo: '3',
        descripcion: 'Combinación de dos shots, Espresso Roast con una proporción mayor de agua.',
        img: '/assets/coffees-images/espresso-lungo.png',
        precio: 40,
        isInOferta: false,
    },
    {
        id: 4,
        nombre: 'Espresso',
        codigo: '4',
        descripcion: 'Es la verdadera esencia del café en la forma más concentrada. El espresso es intenso y fuerte con un toque acaramelado.',
        img: '/assets/coffees-images/espresso.png',
        precio: 45,
        isInOferta: false,
    },
    {
      id: 5,
      nombre: 'Espresso Macchiato',
      codigo: '5',
      descripcion: 'Bebida que combina dos shots de café Espresso Roast con nuna fina capa de espuma de leche perfectamente vaporizada.',
      img: '/assets/coffees-images/espresso-macchiato.png',
      precio: 65,
      isInOferta: false,
    },
    {
      id: 6,
      nombre: 'Espresso Doppio',
      codigo: '6',
      descripcion: 'Bebida preparada con dos shots de Espresso Roast, otorgándole un dulzor intenso y acaramelado.',
      img: '/assets/coffees-images/espresso-doppio.png',
      precio: 65,
      isInOferta: false,
    },
    {
      id: 7,
      nombre: 'Espresso Panna',
      codigo: '7',
      descripcion: 'Dulce e intenso café Espresso, coronado con crema batida.',
      img: '/assets/coffees-images/espresso-panna.png',
      precio: 70,
      isInOferta: false,
    },
    {
      id: 8,
      nombre: 'Skinny Caramel Macchiatto',
      codigo: '8',
      descripcion: 'Leche descremada al vapor "manchada" con espresso y vainilla sugar free, cubierta con un característico dibujo de caramelo.',
      img: '/assets/coffees-images/skinny-caramel-macchiatto.png',
      precio: 69,
      precioAnterior: 80,
      isInOferta: true,
    },
    {
      id: 9,
      nombre: 'Caramel Macchiato',
      codigo: '9',
      descripcion: 'Leche descremada al vapor "manchada" con espresso y vainilla, cubierta con un característico dibujo de caramelo.',
      img: '/assets/coffees-images/caramel-macchiato.png',
      precio: 45,
      isInOferta: false,
    },
    {
      id: 10,
      nombre: 'Latte',
      codigo: '10',
      descripcion: 'Combinación de café espresso con perfecta leche vaporizada. Animate a personalizarlo con sabor a: caramelo, almendra, avellanas, entre otros.',
      img: '/assets/coffees-images/latte.png',
      precio: 80,
      isInOferta: false,
    },
    {
      id: 11,
      nombre: 'Cinnamon Dolce Latte',
      codigo: '11',
      descripcion: 'Exquisita combinación de canela, café Espresso, leche vaporizada, coronado con crema batida y espolvoreado con canela.',
      img: '/assets/coffees-images/cinnamon-dolce-latte.png',
      precio: 100,
      precioAnterior: 110,
      isInOferta: true,
    },
    {
      id: 12,
      nombre: 'Latte Macchiato',
      codigo: '12',
      descripcion: 'Combinación de leche finamente vaporizada y shots de Espresso Roast, finalizado con un punto de café.',
      img: '/assets/coffees-images/latte-macchiato.png',
      precio: 100,
      isInOferta: false,
    },
    {
      id: 13,
      nombre: 'Skinny Vanilla Latte',
      codigo: '13',
      descripcion: 'Delicioso café espresso con leche descremada al vapor y toques de vainilla sin azúcar. Todo esto coronado una sutil capa de espuma de leche.',
      img: '/assets/coffees-images/skinny-vanilla-latte.png',
      precio: 75,
      isInOferta: false,
    },
    {
      id: 14,
      nombre: 'Cocoa Cappaccino',
      codigo: '14',
      descripcion: 'Una exquisita bebida espresso con base de chocolate y la medida justa de leche espumada. Decorada con una rejilla de mocha y finalizada con chocolate espolvoreado.',
      img: '/assets/coffees-images/cocoa-cappaccino.png',
      precio: 70,
      precioAnterior: 90,
      isInOferta: true,
    },
    {
      id: 15,
      nombre: 'Cortado',
      codigo: '15',
      descripcion: 'Delicioso espresso lungo, combinado con una perfecta capa de espuma vaporizada a la perfección.',
      img: '/assets/coffees-images/cortado.png',
      precio: 35,
      isInOferta: false,
    },
    {
      id: 16,
      nombre: 'Dulce de leche Latte',
      codigo: '16',
      descripcion: 'Café espresso con delicioso dulce de leche, leche al vapor con un remolino de crema batida y salsa de caramelo.',
      img: '/assets/coffees-images/dulce-de-leche-latte.png',
      precio: 56,
      isInOferta: false,
    },
    {
      id: 17,
      nombre: 'Flat White',
      codigo: '17',
      descripcion: 'Bebida preparada con shots de ristretto, leche finamente vaporizada, finalizada con un punto.',
      img: '/assets/coffees-images/flat-white.png',
      precio: 123,
      isInOferta: false,
    }
]